apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ros-ocp.fullname" . }}-cdapp-config
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
data:
  cdappconfig.json: |
    {
      "database": {
        "adminPassword": "postgres",
        "adminUsername": "postgres",
        "hostname": "{{ include "ros-ocp.fullname" . }}-db-ros",
        "name": "postgres",
        "password": "postgres",
        "port": {{ .Values.database.ros.port }},
        "username": "postgres",
        "sslMode": "disable"
      },
      "kafka": {
        "brokers": [
          {
            "hostname": "{{ include "ros-ocp.fullname" . }}-kafka",
            "port": {{ .Values.kafka.broker.port }}
          }
        ],
        "topics": [
          {
            "name": "hccm.ros.events",
            "requestedName": "hccm.ros.events"
          },
          {
            "name": "rosocp.kruize.recommendations",
            "requestedName": "rosocp.kruize.recommendations"
          },
          {
            "name": "platform.sources.event-stream",
            "requestedName": "platform.sources.event-stream"
          }
        ]
      },
      "logging": {
        "type": "null"
      },
      "metricsPath": "/metrics",
      "metricsPort": 9000,
      "privatePort": 10000,
      "publicPort": 8000,
      "webPort": 8000
    }