apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ros-ocp.fullname" . }}-rosocp-processor
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: processor
    app.kubernetes.io/name: rosocp-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ros-ocp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: processor
      app.kubernetes.io/name: rosocp-processor
  template:
    metadata:
      labels:
        {{- include "ros-ocp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: processor
        app.kubernetes.io/name: rosocp-processor
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-db-ros
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              until nc -z {{ include "ros-ocp.fullname" . }}-db-ros {{ .Values.database.ros.port }}; do
                echo "Waiting for ROS database..."
                sleep 5
              done
              echo "ROS database is ready"
        - name: wait-for-kafka
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              until nc -z {{ include "ros-ocp.fullname" . }}-kafka {{ .Values.kafka.broker.port }}; do
                echo "Waiting for Kafka..."
                sleep 5
              done
              echo "Kafka is ready"
        - name: wait-for-kruize
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              until nc -z {{ include "ros-ocp.fullname" . }}-kruize {{ .Values.kruize.port }}; do
                echo "Waiting for Kruize..."
                sleep 5
              done
              echo "Kruize is ready"
      containers:
        - name: rosocp-processor
          image: "{{ .Values.rosocp.processor.image.repository }}:{{ .Values.rosocp.processor.image.tag }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              echo 'Waiting for dependencies (Kafka, Kruize) to be ready...'
              sleep 60
              echo 'Starting processor...'
              ./rosocp db migrate up
              ./rosocp start processor
          ports:
            - name: metrics
              containerPort: {{ .Values.rosocp.processor.metricsPort }}
              protocol: TCP
          volumeMounts:
            - name: cdapp-config
              mountPath: /cdapp
              readOnly: true
          env:
            - name: CLOWDER_ENABLED
              value: {{ .Values.rosocp.processor.env.CLOWDER_ENABLED | quote }}
            - name: DB_HOST
              value: {{ include "ros-ocp.fullname" . }}-db-ros
            - name: DB_PORT
              value: {{ .Values.rosocp.processor.env.DB_PORT | quote }}
            - name: DB_NAME
              value: {{ .Values.rosocp.processor.env.DB_NAME | quote }}
            - name: DB_USER
              value: {{ .Values.rosocp.processor.env.DB_USER | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ros-ocp.fullname" . }}-db-credentials
                  key: ros-password
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ include "ros-ocp.fullname" . }}-kafka:{{ .Values.kafka.broker.port }}
            - name: KAFKA_CONSUMER_GROUP_ID
              value: {{ .Values.rosocp.processor.env.KAFKA_CONSUMER_GROUP_ID | quote }}
            - name: KAFKA_AUTO_COMMIT
              value: {{ .Values.rosocp.processor.env.KAFKA_AUTO_COMMIT | quote }}
            - name: UPLOAD_TOPIC
              value: {{ .Values.rosocp.processor.env.UPLOAD_TOPIC | quote }}
            - name: KRUIZE_HOST
              value: {{ include "ros-ocp.fullname" . }}-kruize
            - name: KRUIZE_PORT
              value: {{ .Values.rosocp.processor.env.KRUIZE_PORT | quote }}
            - name: KRUIZE_WAIT_TIME
              value: {{ .Values.rosocp.processor.env.KRUIZE_WAIT_TIME | quote }}
            - name: SERVICE_NAME
              value: {{ .Values.rosocp.processor.env.SERVICE_NAME | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.rosocp.processor.env.LOG_LEVEL | quote }}
            - name: SOURCES_API_BASE_URL
              value: http://{{ include "ros-ocp.fullname" . }}-sources-api:{{ .Values.sourcesApi.port }}
            - name: PROMETHEUS_PORT
              value: {{ .Values.rosocp.processor.env.PROMETHEUS_PORT | quote }}
          # Re-enable probes now that PROMETHEUS_PORT environment variable is correctly set
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9000
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            {{- toYaml .Values.resources.application | nindent 12 }}
      volumes:
        - name: cdapp-config
          configMap:
            name: {{ include "ros-ocp.fullname" . }}-cdapp-config