apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ros-ocp.fullname" . }}-sources-credentials
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
type: Opaque
data:
  encryption-key: {{ .Values.sourcesApi.env.ENCRYPTION_KEY | b64enc }}