# OpenShift-specific values for ROS-OCP deployment
# Uses OpenShift Routes instead of Kubernetes Ingress

global:
  # Storage class will be auto-detected (should use default ocs-storagecluster-ceph-rbd)
  storageClass: ""
  pullPolicy: IfNotPresent
  imagePullSecrets: []

# Reduce resource requirements for testing environment
resources:
  database:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  kafka:
    requests:
      memory: "1Gi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

  zookeeper:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  kruize:
    requests:
      memory: "1Gi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

# Use smaller storage sizes for testing
database:
  ros:
    storage:
      size: "5Gi"
  kruize:
    storage:
      size: "5Gi"
  sources:
    storage:
      size: "5Gi"

kafka:
  broker:
    storage:
      size: "5Gi"
  zookeeper:
    storage:
      size: "3Gi"

minio:
  storage:
    size: "10Gi"

# OpenShift Routes configuration (automatically used when deploying to OpenShift)
serviceRoute:
  enabled: true
  annotations:
    # OpenShift-specific route annotations
    haproxy.router.openshift.io/timeout: "300s"
    haproxy.router.openshift.io/rewrite-target: ""
  hosts:
    - host: ""  # Empty host uses cluster's default route domain
      paths:
        - path: /
          pathType: Prefix
  tls:
    # Uncomment to enable TLS termination
    # termination: edge
    # insecureEdgeTerminationPolicy: Redirect