apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ros-ocp.fullname" . }}-kruize-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
data:
  cdappconfig.json: |
    {
      "database": {
        "adminPassword": "{{ .Values.database.kruize.adminPassword }}",
        "adminUsername": "{{ .Values.database.kruize.adminUser }}",
        "hostname": "{{ include "ros-ocp.kruizeDatabaseHost" . }}",
        "name": "{{ .Values.database.kruize.name }}",
        "password": "{{ .Values.database.kruize.password }}",
        "port": {{ .Values.database.kruize.port }},
        "username": "{{ .Values.database.kruize.user }}",
        "sslMode": "{{ .Values.database.kruize.sslMode }}"
      },
      "kafka": {
        "brokers": [
          {
            "authtype": "sasl",
            "hostname": "{{ include "ros-ocp.fullname" . }}-kafka",
            "port": {{ .Values.kafka.broker.port }},
            "sasl": {
              "password": "",
              "saslMechanism": "PLAIN",
              "securityProtocol": "SSL",
              "username": ""
            },
            "securityProtocol": "SSL",
            "cacert": "-----BEGIN CERTIFICATE-----\nMIIDvTCCAqWgAwIBAgIUctrqAnBFhUmpF7Yti5AJW7dCnAUwDQYJKoZIhvcNAQEL\nBQAwbTESMBAGA1UEAwwJY2ExLmxvY2FsMRQwEgYDVQQLDAtteS1vcmctdW5pdDEP\nMA0GA1UECgwGbXktb3JnMRAwDgYDVQQHDAdteS1jaXR5MREwDwYDVQQIDAhteS1z\ndGF0ZTELMAkGA1UEBhMCQVUwIBcNMjQwMTAyMDgzNjM4WhgPMjA1MTA1MTkwODM2\nMzhaMG0xEjAQBgNVBAMMCWNhMS5sb2NhbDEUMBIGA1UECwwLbXktb3JnLXVuaXQx\nDzANBgNVBAoMBm15LW9yZzEQMA4GA1UEBwwHbXktY2l0eTERMA8GA1UECAwIbXkt\nc3RhdGUxCzAJBgNVBAYTAkFVMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC\nAQEAs3pAov4jmDyxd+aPQR6KyzACBjHFOQZ/kGk5bZYX1BCTIkCOw802ydzbfdRg\nSCLM1fukn8MyVLM0Lv2JhJe+Ev68ZfbgCTgYiayksyZH1kyOmUAJhsk+mAse/kCW\nP4uxdnNPIWc9Fb+hthYblf7nXUh0h+9rUNItLNay7eiTJe8/pUWZevwJwFL1fgjo\nsNhZAbvBk0yr3j8IlXpa0je8NPFuhoCQtpwHtzeFK8ntGjs9bjV8OjL5nHCwOlWe\naVUr/twGPZLLyYCKGsSejs/gS64gLVOfd9huHf2fZ/loXa4yJT12MSAieGLJ3eNA\n2VXA526y+oof+ePIyOoode5cfwIDAQABo1MwUTAdBgNVHQ4EFgQUzgMMah64ZL1D\n/CKiBYfVeWJ3ttMwHwYDVR0jBBgwFoAUzgMMah64ZL1D/CKiBYfVeWJ3ttMwDwYD\nVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAiuTGQG1nU7Q+cjfVbEjS\nYykiY0Nb0E0EKCnKO3B96s7efw9wOgQ7m5U0Vtz4o67LTIWFYcD5iQIyv5xmWYux\nGSWH+BKIFs9uy5ZEPlLsX/YZEIIy+2nLjP5v5+DJdDZrJPIr8Yb5Mb6YybVjTkgQ\nXqbo0CbdDTRU6Gx5O1GptydzKCtmfJZw+Xh4SCQktzI8R9+iANjXKWEo3oeF/yMv\neMYAwOVauUbncdhV4oE7HewFABYdZfUmW4eWKw0MW6J7rq0/nUBdX3tQkJ2pGl5i\n5wKQJ5X00I9r60u6tOd5uRalnNu6wVywlrC4+YVpOyK7iXnC7MnCKCv/8acpxKW0\njw==\n-----END CERTIFICATE-----"
          }
        ],
        "topics": [
          {
            "name": "{{ .Values.rosocp.processor.uploadTopic }}",
            "requestedName": "{{ .Values.rosocp.processor.uploadTopic }}"
          },
          {
            "name": "{{ .Values.rosocp.recommendationPoller.recommendationTopic }}",
            "requestedName": "{{ .Values.rosocp.recommendationPoller.recommendationTopic }}"
          },
          {
            "name": "{{ .Values.sourcesApi.platformSourcesEventStreamTopic }}",
            "requestedName": "{{ .Values.sourcesApi.platformSourcesEventStreamTopic }}"
          }
        ]
      },
      "logging": {
        "cloudwatch": {
          "accessKeyId": "",
          "logGroup": "",
          "region": "",
          "secretAccessKey": ""
        },
        "type": "null"
      },
      "metricsPath": "/metrics",
      "metricsPort": 9000,
      "privatePort": 10000,
      "publicPort": 8000,
      "webPort": 8000
    }