apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ros-ocp.fullname" . }}-cdapp-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
data:
  cdappconfig.json: |
    {
      "database": {
        "adminPassword": "{{ .Values.database.ros.password }}",
        "adminUsername": "{{ .Values.database.ros.user }}",
        "hostname": "{{ include "ros-ocp.databaseHost" . }}",
        "name": "{{ .Values.database.ros.name }}",
        "password": "{{ .Values.database.ros.password }}",
        "port": {{ .Values.database.ros.port }},
        "username": "{{ .Values.database.ros.user }}",
        "sslMode": "{{ .Values.database.ros.sslMode }}"
      },
      "kafka": {
        "brokers": [
          {
            "hostname": "{{ include "ros-ocp.fullname" . }}-kafka",
            "port": {{ .Values.kafka.broker.port }}
          }
        ],
        "topics": [
          {
            "name": "{{ .Values.rosocp.processor.uploadTopic }}",
            "requestedName": "{{ .Values.rosocp.processor.uploadTopic }}"
          },
          {
            "name": "{{ .Values.rosocp.recommendationPoller.recommendationTopic }}",
            "requestedName": "{{ .Values.rosocp.recommendationPoller.recommendationTopic }}"
          },
          {
            "name": "{{ .Values.sourcesApi.platformSourcesEventStreamTopic }}",
            "requestedName": "{{ .Values.sourcesApi.platformSourcesEventStreamTopic }}"
          }
        ]
      },
      "logging": {
        "type": "null"
      },
      "metricsPath": "/metrics",
      "metricsPort": 9000,
      "privatePort": 10000,
      "publicPort": 8000,
      "webPort": 8000
    }