{{/* Deploy ingress service on both Kubernetes and OpenShift */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ros-ocp.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress
    app.kubernetes.io/name: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ros-ocp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ingress
      app.kubernetes.io/name: ingress
  template:
    metadata:
      labels:
        {{- include "ros-ocp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ingress
        app.kubernetes.io/name: ingress
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-minio
          image: "{{ .Values.global.initContainers.waitFor.repository }}:{{ .Values.global.initContainers.waitFor.tag }}"
          command: ['bash', '-c']
          args:
            - |
              echo "Waiting for MinIO at {{ include "ros-ocp.fullname" . }}-minio:{{ .Values.minio.ports.api }}..."
              until timeout 3 bash -c "echo > /dev/tcp/{{ include "ros-ocp.fullname" . }}-minio/{{ .Values.minio.ports.api }}" 2>/dev/null; do
                echo "MinIO not ready yet, retrying in 5 seconds..."
                sleep 5
              done
              echo "MinIO is ready"
              echo "MinIO is ready"
        - name: wait-for-kafka
          image: "{{ .Values.global.initContainers.waitFor.repository }}:{{ .Values.global.initContainers.waitFor.tag }}"
          command: ['bash', '-c']
          args:
            - |
              echo "Waiting for Kafka at {{ include "ros-ocp.fullname" . }}-kafka:{{ .Values.kafka.broker.port }}..."
              until timeout 3 bash -c "echo > /dev/tcp/{{ include "ros-ocp.fullname" . }}-kafka/{{ .Values.kafka.broker.port }}" 2>/dev/null; do
                echo "Kafka not ready yet, retrying in 5 seconds..."
                sleep 5
              done
              echo "Kafka is ready"
              echo "Kafka is ready"
      serviceAccountName: insights-ros-ingress
      containers:
        - name: ingress
          image: "{{ .Values.ingress.image.repository }}:{{ .Values.ingress.image.tag }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ingress.port }}
              protocol: TCP
          env:
            # Server configuration
            - name: SERVER_PORT
              value: {{ .Values.ingress.server.port | quote }}
            - name: SERVER_READ_TIMEOUT
              value: {{ .Values.ingress.server.readTimeout | quote }}
            - name: SERVER_WRITE_TIMEOUT
              value: {{ .Values.ingress.server.writeTimeout | quote }}
            - name: SERVER_IDLE_TIMEOUT
              value: {{ .Values.ingress.server.idleTimeout | quote }}
            - name: DEBUG
              value: {{ .Values.ingress.server.debug | quote }}

            # Upload configuration
            - name: UPLOAD_MAX_SIZE
              value: {{ .Values.ingress.upload.maxUploadSize | quote }}
            - name: UPLOAD_MAX_MEMORY
              value: {{ .Values.ingress.upload.maxMemory | quote }}
            - name: UPLOAD_TEMP_DIR
              value: {{ .Values.ingress.upload.tempDir | quote }}
            - name: UPLOAD_ALLOWED_TYPES
              value: {{ join "," .Values.ingress.upload.allowedTypes | quote }}
            - name: UPLOAD_REQUIRE_AUTH
              value: {{ .Values.ingress.upload.requireAuth | quote }}

            # Storage configuration
            - name: STORAGE_ENDPOINT
              value: {{ include "ros-ocp.fullname" . }}-minio:{{ .Values.minio.ports.api }}
            - name: STORAGE_BUCKET
              value: {{ .Values.ingress.storage.bucket | quote }}
            - name: STORAGE_USE_SSL
              value: {{ .Values.ingress.storage.useSSL | quote }}
            - name: STORAGE_URL_EXPIRATION
              value: {{ .Values.ingress.storage.urlExpiration | quote }}
            - name: STORAGE_PATH_PREFIX
              value: {{ .Values.ingress.storage.pathPrefix | quote }}
            - name: STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ros-ocp.fullname" . }}-minio-credentials
                  key: access-key
            - name: STORAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ros-ocp.fullname" . }}-minio-credentials
                  key: secret-key

            # Kafka configuration
            - name: KAFKA_BROKERS
              value: {{ include "ros-ocp.fullname" . }}-kafka:{{ .Values.kafka.broker.port }}
            - name: KAFKA_ROS_TOPIC
              value: {{ .Values.ingress.kafka.topic | quote }}
            - name: KAFKA_SECURITY_PROTOCOL
              value: {{ .Values.ingress.kafka.securityProtocol | quote }}
            - name: KAFKA_CLIENT_ID
              value: {{ .Values.ingress.kafka.clientId | quote }}
            - name: KAFKA_BATCH_SIZE
              value: {{ .Values.ingress.kafka.batchSize | quote }}
            - name: KAFKA_RETRIES
              value: {{ .Values.ingress.kafka.retries | quote }}

            # Authentication configuration
            - name: AUTH_ENABLED
              value: {{ .Values.ingress.auth.enabled | quote }}
            - name: JWT_SECRET
              value: {{ .Values.ingress.auth.jwtSecret | quote }}

            # Logging configuration
            - name: LOG_LEVEL
              value: {{ .Values.ingress.logging.level | quote }}
            - name: LOG_FORMAT
              value: {{ .Values.ingress.logging.format | quote }}
            - name: LOG_OUTPUT
              value: {{ .Values.ingress.logging.output | quote }}

            # Metrics configuration
            - name: METRICS_ENABLED
              value: {{ .Values.ingress.metrics.enabled | quote }}
            - name: METRICS_PATH
              value: {{ .Values.ingress.metrics.path | quote }}
            - name: METRICS_PORT
              value: {{ .Values.ingress.metrics.port | quote }}

            # HCCM Validation configuration
            # Platform-specific validation settings: disabled for KIND/development, enabled for OpenShift/production
            - name: HCCM_VALIDATION_ENABLED
              value: {{ if eq (include "ros-ocp.isOpenShift" .) "true" }}"true"{{ else }}"false"{{ end }}
            - name: HCCM_VALIDATION_SERVICE_URL
              value: {{ if eq (include "ros-ocp.isOpenShift" .) "true" }}{{ .Values.ingress.validation.hccm.serviceUrl | quote }}{{ else }}""{{ end }}
            - name: HCCM_VALIDATION_TIMEOUT
              value: {{ .Values.ingress.validation.hccm.timeout | quote }}
            - name: HCCM_VALIDATION_RETRIES
              value: {{ .Values.ingress.validation.hccm.retries | quote }}
            - name: PLATFORM_MODE
              value: {{ if eq (include "ros-ocp.isOpenShift" .) "true" }}"production"{{ else }}"development"{{ end }}
            - name: VALIDATION_BYPASS_MODE
              value: {{ if eq (include "ros-ocp.isOpenShift" .) "true" }}"false"{{ else }}"true"{{ end }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ingress.port }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.ingress.port }}
            initialDelaySeconds: 10
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
          resources:
            {{- toYaml .Values.resources.application | nindent 12 }}