apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ros-ocp.fullname" . }}-rosocp-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    app.kubernetes.io/name: rosocp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ros-ocp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
      app.kubernetes.io/name: rosocp-api
  template:
    metadata:
      labels:
        {{- include "ros-ocp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
        app.kubernetes.io/name: rosocp-api
    spec:
      serviceAccountName: {{ include "ros-ocp.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-db-ros
          image: "{{ .Values.global.initContainers.waitFor.repository }}:{{ .Values.global.initContainers.waitFor.tag }}"
          command: ['bash', '-c']
          args:
            - |
              echo "Waiting for ROS database at {{ include "ros-ocp.fullname" . }}-db-ros:{{ .Values.database.ros.port }}..."
              until timeout 3 bash -c "echo > /dev/tcp/{{ include "ros-ocp.fullname" . }}-db-ros/{{ .Values.database.ros.port }}" 2>/dev/null; do
                echo "Database not ready yet, retrying in 5 seconds..."
                sleep 5
              done
              echo "ROS database is ready"
              echo "ROS database is ready"
        - name: wait-for-kafka
          image: "{{ .Values.global.initContainers.waitFor.repository }}:{{ .Values.global.initContainers.waitFor.tag }}"
          command: ['bash', '-c']
          args:
            - |
              echo "Waiting for Kafka at {{ include "ros-ocp.fullname" . }}-kafka:{{ .Values.kafka.broker.port }}..."
              until timeout 3 bash -c "echo > /dev/tcp/{{ include "ros-ocp.fullname" . }}-kafka/{{ .Values.kafka.broker.port }}" 2>/dev/null; do
                echo "Kafka not ready yet, retrying in 5 seconds..."
                sleep 5
              done
              echo "Kafka is ready"
              echo "Kafka is ready"
      containers:
        - name: rosocp-api
          image: "{{ .Values.rosocp.api.image.repository }}:{{ .Values.rosocp.api.image.tag }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              ./rosocp db migrate up
              ./rosocp start api
          ports:
            - name: http
              containerPort: {{ .Values.rosocp.api.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.rosocp.api.metricsPort }}
              protocol: TCP
          env:
            - name: PATH_PREFIX
              value: {{ .Values.rosocp.api.pathPrefix | quote }}
            - name: CLOWDER_ENABLED
              value: "false"
            - name: RBAC_ENABLE
              value: {{ .Values.rosocp.api.rbacEnable | quote }}
            - name: DB_POOL_SIZE
              value: {{ .Values.rosocp.api.dbPoolSize | quote }}
            - name: DB_MAX_OVERFLOW
              value: {{ .Values.rosocp.api.dbMaxOverflow | quote }}
            - name: SERVICE_NAME
              value: {{ .Values.rosocp.api.serviceName | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.rosocp.api.logLevel | quote }}
            - name: DB_HOST
              value: {{ include "ros-ocp.databaseHost" (list . "ros") }}
            - name: DB_PORT
              value: {{ .Values.database.ros.port | quote }}
            - name: DB_NAME
              value: {{ .Values.database.ros.name | quote }}
            - name: DB_USER
              value: {{ .Values.database.ros.user | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ros-ocp.fullname" . }}-db-credentials
                  key: ros-password
            - name: DATABASE_URL
              value: {{ include "ros-ocp.databaseUrl" . }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ include "ros-ocp.fullname" . }}-kafka:{{ .Values.kafka.broker.port }}
            - name: ID_PROVIDER
              value: {{ .Values.auth.provider | quote }}
          livenessProbe:
            httpGet:
              path: /status
              port: {{ .Values.rosocp.api.port }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /status
              port: {{ .Values.rosocp.api.port }}
            initialDelaySeconds: 15
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
          resources:
            {{- toYaml .Values.resources.application | nindent 12 }}