apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ros-ocp.fullname" . }}-rosocp-housekeeper
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: housekeeper
    app.kubernetes.io/name: rosocp-housekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ros-ocp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: housekeeper
      app.kubernetes.io/name: rosocp-housekeeper
  template:
    metadata:
      labels:
        {{- include "ros-ocp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: housekeeper
        app.kubernetes.io/name: rosocp-housekeeper
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-db-ros
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              until nc -z {{ include "ros-ocp.fullname" . }}-db-ros {{ .Values.database.ros.port }}; do
                echo "Waiting for ROS database..."
                sleep 5
              done
              echo "ROS database is ready"
        - name: wait-for-kafka
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              until nc -z {{ include "ros-ocp.fullname" . }}-kafka {{ .Values.kafka.broker.port }}; do
                echo "Waiting for Kafka..."
                sleep 5
              done
              echo "Kafka is ready"
        - name: wait-for-kruize
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              until nc -z {{ include "ros-ocp.fullname" . }}-kruize {{ .Values.kruize.port }}; do
                echo "Waiting for Kruize..."
                sleep 5
              done
              echo "Kruize is ready"
        - name: wait-for-sources-api
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              until nc -z {{ include "ros-ocp.fullname" . }}-sources-api {{ .Values.sourcesApi.port }}; do
                echo "Waiting for Sources API..."
                sleep 5
              done
              echo "Sources API is ready"
      containers:
        - name: rosocp-housekeeper
          image: "{{ .Values.rosocp.housekeeper.image.repository }}:{{ .Values.rosocp.housekeeper.image.tag }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              echo 'Waiting for dependencies (Kafka) to be ready...'
              sleep 60
              echo 'Starting housekeeper...'
              ./rosocp db migrate up
              ./rosocp start housekeeper --sources
          env:
            - name: CLOWDER_ENABLED
              value: "false"
            - name: KRUIZE_HOST
              value: {{ include "ros-ocp.fullname" . }}-kruize
            - name: KRUIZE_PORT
              value: {{ .Values.rosocp.housekeeper.env.KRUIZE_PORT | quote }}
            - name: SERVICE_NAME
              value: {{ .Values.rosocp.housekeeper.env.SERVICE_NAME | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.rosocp.housekeeper.env.LOG_LEVEL | quote }}
            - name: DB_HOST
              value: {{ include "ros-ocp.databaseHost" . }}
            - name: DB_PORT
              value: {{ .Values.rosocp.database.port | quote }}
            - name: DB_NAME
              value: {{ .Values.rosocp.database.name | quote }}
            - name: DB_USER
              value: {{ .Values.rosocp.database.user | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ros-ocp.fullname" . }}-db-credentials
                  key: ros-password
            - name: DATABASE_URL
              value: {{ include "ros-ocp.databaseUrl" . }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ include "ros-ocp.fullname" . }}-kafka:{{ .Values.kafka.broker.port }}
            - name: SOURCES_API_BASE_URL
              value: http://{{ include "ros-ocp.fullname" . }}-sources-api:{{ .Values.sourcesApi.port }}
          resources:
            {{- toYaml .Values.resources.application | nindent 12 }}