apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ros-ocp.fullname" . }}-rosocp-housekeeper
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: housekeeper
    app.kubernetes.io/name: rosocp-housekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ros-ocp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: housekeeper
      app.kubernetes.io/name: rosocp-housekeeper
  template:
    metadata:
      labels:
        {{- include "ros-ocp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: housekeeper
        app.kubernetes.io/name: rosocp-housekeeper
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-db-ros
          image: "{{ .Values.global.initContainers.waitFor.repository }}:{{ .Values.global.initContainers.waitFor.tag }}"
          command: ['bash', '-c']
          args:
            - |
              echo "Waiting for ROS database at {{ include "ros-ocp.fullname" . }}-db-ros:{{ .Values.database.ros.port }}..."
              until timeout 3 bash -c "echo > /dev/tcp/{{ include "ros-ocp.fullname" . }}-db-ros/{{ .Values.database.ros.port }}" 2>/dev/null; do
                echo "Database not ready yet, retrying in 5 seconds..."
                sleep 5
              done
              echo "ROS database is ready"
              echo "ROS database is ready"
        - name: wait-for-kafka
          image: "{{ .Values.global.initContainers.waitFor.repository }}:{{ .Values.global.initContainers.waitFor.tag }}"
          command: ['bash', '-c']
          args:
            - |
              echo "Waiting for Kafka at {{ include "ros-ocp.fullname" . }}-kafka:{{ .Values.kafka.broker.port }}..."
              until timeout 3 bash -c "echo > /dev/tcp/{{ include "ros-ocp.fullname" . }}-kafka/{{ .Values.kafka.broker.port }}" 2>/dev/null; do
                echo "Kafka not ready yet, retrying in 5 seconds..."
                sleep 5
              done
              echo "Kafka is ready"
              echo "Kafka is ready"
        - name: wait-for-kruize
          image: "{{ .Values.global.initContainers.waitFor.repository }}:{{ .Values.global.initContainers.waitFor.tag }}"
          command: ['bash', '-c']
          args:
            - |
              echo "Waiting for Kruize at {{ include "ros-ocp.fullname" . }}-kruize:{{ .Values.kruize.port }}..."
              until timeout 3 bash -c "echo > /dev/tcp/{{ include "ros-ocp.fullname" . }}-kruize/{{ .Values.kruize.port }}" 2>/dev/null; do
                echo "Kruize not ready yet, retrying in 5 seconds..."
                sleep 5
              done
              echo "Kruize is ready"
              echo "Kruize is ready"
        - name: wait-for-sources-api
          image: "{{ .Values.global.initContainers.waitFor.repository }}:{{ .Values.global.initContainers.waitFor.tag }}"
          command: ['bash', '-c']
          args:
            - |
              echo "Waiting for Sources API at {{ include "ros-ocp.fullname" . }}-sources-api:{{ .Values.sourcesApi.port }}..."
              until timeout 3 bash -c "echo > /dev/tcp/{{ include "ros-ocp.fullname" . }}-sources-api/{{ .Values.sourcesApi.port }}" 2>/dev/null; do
                echo "Sources API not ready yet, retrying in 5 seconds..."
                sleep 5
              done
              echo "Sources API is ready"
              echo "Sources API is ready"
      containers:
        - name: rosocp-housekeeper
          image: "{{ .Values.rosocp.housekeeper.image.repository }}:{{ .Values.rosocp.housekeeper.image.tag }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              echo 'Waiting for dependencies (Kafka) to be ready...'
              sleep 60
              echo 'Starting housekeeper...'
              ./rosocp db migrate up
              ./rosocp start housekeeper --sources
          env:
            - name: CLOWDER_ENABLED
              value: "false"
            - name: KRUIZE_HOST
              value: {{ include "ros-ocp.fullname" . }}-kruize
            - name: KRUIZE_PORT
              value: {{ .Values.kruize.port | quote }}
            - name: SERVICE_NAME
              value: {{ .Values.rosocp.housekeeper.serviceName | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.rosocp.housekeeper.logLevel | quote }}
            - name: DB_HOST
              value: {{ include "ros-ocp.databaseHost" . }}
            - name: DB_PORT
              value: {{ .Values.database.ros.port | quote }}
            - name: DB_NAME
              value: {{ .Values.database.ros.name | quote }}
            - name: DB_USER
              value: {{ .Values.database.ros.user | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ros-ocp.fullname" . }}-db-credentials
                  key: ros-password
            - name: DATABASE_URL
              value: {{ include "ros-ocp.databaseUrl" . }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ include "ros-ocp.fullname" . }}-kafka:{{ .Values.kafka.broker.port }}
            - name: SOURCES_API_BASE_URL
              value: http://{{ include "ros-ocp.fullname" . }}-sources-api:{{ .Values.sourcesApi.port }}
          resources:
            {{- toYaml .Values.resources.application | nindent 12 }}