apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ros-ocp.fullname" . }}-kafka-topics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: setup
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "ros-ocp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: setup
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-kafka
          image: "{{ .Values.global.initContainers.waitFor.repository }}:{{ .Values.global.initContainers.waitFor.tag }}"
          command: ['bash', '-c']
          args:
            - |
              echo "Waiting for Kafka at {{ include "ros-ocp.fullname" . }}-kafka:{{ .Values.kafka.broker.port }}..."
              until timeout 3 bash -c "echo > /dev/tcp/{{ include "ros-ocp.fullname" . }}-kafka/{{ .Values.kafka.broker.port }}" 2>/dev/null; do
                echo "Kafka not ready yet, retrying in 5 seconds..."
                sleep 5
              done
              echo "Kafka is ready"
      containers:
        - name: kafka-topics
          image: "{{ .Values.kafka.broker.image.repository }}:{{ .Values.kafka.broker.image.tag }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          command: ["bash", "-c"]
          args:
            - |
              echo "Waiting for Kafka to be ready..."
              cub kafka-ready -b {{ include "ros-ocp.fullname" . }}-kafka:{{ .Values.kafka.broker.port }} 1 20
              echo "Creating topics..."
              kafka-topics --create --if-not-exists --topic hccm.ros.events --bootstrap-server {{ include "ros-ocp.fullname" . }}-kafka:{{ .Values.kafka.broker.port }}
              kafka-topics --create --if-not-exists --topic platform.sources.event-stream --bootstrap-server {{ include "ros-ocp.fullname" . }}-kafka:{{ .Values.kafka.broker.port }}
              kafka-topics --create --if-not-exists --topic rosocp.kruize.recommendations --bootstrap-server {{ include "ros-ocp.fullname" . }}-kafka:{{ .Values.kafka.broker.port }}
              echo "Topics created successfully"