apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-alias
spec:
  type: ExternalName
  externalName: {{ include "ros-ocp.fullname" . }}-kafka.{{ .Release.Namespace }}.svc.cluster.local
  ports:
    - port: 29092
      targetPort: 29092
      protocol: TCP
      name: kafka