apiVersion: v1
kind: Service
metadata:
  name: {{ include "ros-ocp.fullname" . }}-rosocp-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    app.kubernetes.io/name: rosocp-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.rosocp.api.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.rosocp.api.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "ros-ocp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
    app.kubernetes.io/name: rosocp-api