apiVersion: v1
kind: Service
metadata:
  name: {{ include "ros-ocp.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
    app.kubernetes.io/name: redis
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "ros-ocp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cache
    app.kubernetes.io/name: redis