apiVersion: v1
kind: Service
metadata:
  name: {{ include "ros-ocp.fullname" . }}-kafka
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
    app.kubernetes.io/name: kafka
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.kafka.broker.port }}
      targetPort: kafka
      protocol: TCP
      name: kafka
  selector:
    {{- include "ros-ocp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
    app.kubernetes.io/name: kafka